name: Build and Deploy Repository
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'dist/**'
      - 'README.md'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build
        run: |
          npm install -g skystream-cli
          skystream deploy -u https://raw.githubusercontent.com/${{ github.repository }}/build
          sed -i 's|/build/dist/|/build/|g' dist/*.json

      - name: Deploy to build branch
        run: |
          # 1. Pindahkan (bukan copy) dist ke folder sementara agar lenyap dari repo
          mv dist /tmp/build_result
          
          git checkout -B build
          
          # 2. Hapus file tracked
          git rm -rf . || true
          
          # 3. Hapus bersih semua file untracked yang tersisa (termasuk node_modules)
          git clean -fdx
          
          # 4. Kembalikan HANYA isi dari build_result
          cp -r /tmp/build_result/* .
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: automated deploy [skip ci]" || echo "No changes"
          git push origin build --force